# Generated by Django 4.1.7 on 2023-03-30 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorie_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Consume',
                'verbose_name_plural': 'Consumes',
            },
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbs', models.FloatField()),
                ('protein', models.FloatField()),
                ('fats', models.FloatField()),
                ('calories', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.RemoveField(
            model_name='consume',
            name='food_consumed',
        ),
        migrations.RemoveField(
            model_name='consume',
            name='user',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Consume',
        ),
        migrations.AddField(
            model_name='consumemodel',
            name='food_consumed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie_tracker_app.foodmodel'),
        ),
        migrations.AddField(
            model_name='consumemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
