# Generated by Django 4.1.7 on 2023-03-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker_app', '0002_consumemodel_foodmodel_remove_consume_food_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='calories',
            field=models.IntegerField(max_length=255, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='carbs',
            field=models.FloatField(max_length=255, verbose_name='Carbohydrate'),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='fats',
            field=models.FloatField(max_length=255, verbose_name='Fat'),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='protein',
            field=models.FloatField(max_length=255, verbose_name='Protein'),
        ),
    ]
