# Generated by Django 4.1.7 on 2023-03-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_forumcomments_user_forumpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='user1',
            new_name='user',
        ),
    ]
