# Generated by Django 4.1.7 on 2023-04-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='activity2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
